language: java
branches:
  only:
  - master
  - develop
before_install:
- chmod +x gradlew
install: true
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
script:
- git clone -b master https://github.com/nablarch/nablarch-ci-script.git $HOME/build-script/
  && chmod +x $HOME/build-script/travis-ci/*.sh
- $HOME/build-script/travis-ci/install-oracle-jdk6.sh
- $HOME/build-script/travis-ci/nablarch-build.sh
- $HOME/build-script/travis-ci/upload-test-report.sh
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
notifications:
  slack:
    secure: BCFlET1206oNRJphno60jn5zW+QWK5D5q0Q0Fxx6eX7hV5DGdiJ/wW1+LrMXNKzRxRvANWTmJ09Xi/E8XqIFU488hUa5UmdNU5H1yKNUOacn5NbQXqjwiQLKCZ/E1pCqPJbcxFH5GO2pJARPnDLpOA1gmd1MijrLobNyc3f1H2XnQuzq1C0AVmd4z1+ajb3mELpRPITkNQtuv/OP8E9c7aI9fNJPQb/oTuQzkmbWRccl6fUUkOyakW8Jg6tmjjfnl5epTgwS2Zsd1o9pfEDMR3JhF4yk6JEKMMs9XEvVcyCptzLAZZiFscXOa8kxqhAkurFLrNoa+eGyG0vsFMDWdZNc5u37tXeqnmsQjo73ELSbZfzvQIjmepJ3papx+tkQkFA+rBuEqZGDMsgCWQipsXH3TdTRwTMuISeDEwxO+OxMLHR9kXrhSCeYqAIJrcixi3hlyx8IBZbPbAL5IduEiOxkWSqgmcQyJO5lIGGiEJNUJMapXmqHaIQx3/qVw9V5V81bu6kqWRHzS6tI4RjCkjSuq6RNfQI677oOaLo+/zGc0IVSFnxHv59kX1hJxXliTdZoamyyjQFcUFlUsjWKambMRU3egv/YDbRn0lSryPG/H7HY98dN3kvgJtGTrIuT44o8Ecflcb5tU9c5848L6z3+nNyiVfwVV3qWs0c7yPo=
